### ISSUE TITLE
cannont find .dmp find

### ISSUE THREAD

**Issue by kajal101292** [cmusphinx/sphinxtrain#11]
hi,
i follow the following tutorial
https://cmusphinx.github.io/wiki/tutorialadapt/
In "Adapting the acoustic model " section , it is said to copy en-us.lm.dmp file from source location to my current working directory. But en-us.lm.dmp file is not there in the source location . I have en-us.lm.bin , en-us-phone.lm.bin, cmudict-en-us.dict  files . Is there any alternate option that can be used in place of en-us.lm.dmp file . 
please help

**Comment by nshmyrev** [comment]
use en-us.lm.bin

**Comment by kajal101292** [comment]
ohk. I used en-us.lm.bin file and then i executed this command " sphinx_fe -argfile en-us/feat.params\-samprate 16000 -c arctic20.fileids \-di . -do . -ei wav -eo mfc -mswav yes" 

.mfc files are generated but there is no change in cmudict-en-us.dict and en-us.lm.bin files . The sentences which i recorded where i can see them. How i will access my acoustic model. 
please help.
