### ISSUE TITLE
problem in new acoustic model

### ISSUE THREAD

**Issue by kajal101292** [cmusphinx/sphinxtrain#12]
ohk. I used en-us.lm.bin file and then i executed this command " sphinx_fe -argfile en-us/feat.params\-samprate 16000 -c arctic20.fileids \-di . -do . -ei wav -eo mfc -mswav yes" 

.mfc files are generated but there is no change in cmudict-en-us.dict and en-us.lm.bin files . The sentences which i recorded where i can see them. How i will access my acoustic model. 
please help.

**Comment by kajal101292** [comment]
ohk. I used en-us.lm.bin file and then i executed this command " sphinx_fe -argfile en-us/feat.params-samprate 16000 -c arctic20.fileids -di . -do . -ei wav -eo mfc -mswav yes"

.mfc files are generated but there is no change in cmudict-en-us.dict and en-us.lm.bin files . The sentences which i recorded where i can see them. How i will access my acoustic model.
please help.

**Comment by nshmyrev** [comment]
Use forums for support and try to explain in more details.
