### ISSUE TITLE
Want to set mfc file location in "bw" on commandline

### ISSUE THREAD

**Issue by dnyaneshwar1991** [cmusphinx/sphinxtrain#15]
Hi,

I want to set "mfc" file location in "bw" on commandline.so is there any flag for that?
Actually I wrote one script for all adaption command, and my acoustic model location is diff than my script location. I thought  "-cepext"  will work for me but no it is for mfc extension only.

Thanks in advance.

**Comment by nshmyrev** [comment]
`-cepdir				The cepstrum data root directory`

**Comment by dnyaneshwar1991** [comment]
Thanks a lot...!!!
