### ISSUE TITLE
compilation crashes because of slave_feat.pl

### ISSUE THREAD

**Issue by GuiJordao21** [cmusphinx/sphinxtrain#16]
everytime I try to train my model I get this message:

compilation failed in require at /usr/local/lib/sphinxtrain/scripts/000.comp_feat/slave_feat.pl line 51.
BEGIN failed--compilation aborted at /usr/local/lib/sphinxtrain/scripts/000.comp_feat/slave_feat.pl line 51

anyone have some ideia of what this is??

**Comment by GuiJordao21** [comment]
just saw here I have a configuration not defined message before that.

**Comment by nshmyrev** [comment]
You probably miss setup step.

**Comment by nshmyrev** [comment]
Already asked at https://sourceforge.net/p/cmusphinx/discussion/help/thread/807c6435/
