### ISSUE TITLE
Sphinxtrain make failed on virtualbox and ubuntu : Error in making libclust

### ISSUE THREAD

**Issue by thierry-lc** [cmusphinx/sphinxtrain#20]
Hello,
i have try another sphnxtrain installation on virtualbox and ubuntu , my previous was on Ubuntu for windows. And this time i have the same problem on making sphinxtrain with error on making libclust.

I use the last libtool 2.4.6 and 18.04.1-Ubuntu 
sphinxtrain was the last version like sphinxbase and pocketsphinx.

=========== make sphinxtrain ======

thierry@vmLFR038391:~/pocketsphinx/sphinxtrain-5prealpha$ make
Making all in etc
make[1] : on entre dans le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/etc »
make[1]: rien à faire pour « all ».
make[1] : on quitte le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/etc »
Making all in include
make[1] : on entre dans le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/include »
(CDPATH="${ZSH_VERSION+.}:" && cd .. && /bin/bash /home/thierry/pocketsphinx/sphinxtrain-5prealpha/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd .. && /bin/bash ./config.status include/config.h
config.status: creating include/config.h
config.status: include/config.h is unchanged
make all-am
make[2] : on entre dans le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/include »
make[2] : on quitte le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/include »
make[1] : on quitte le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/include »
Making all in python
make[1] : on entre dans le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/python »
make[1]: rien à faire pour « all ».
make[1] : on quitte le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/python »
Making all in scripts
make[1] : on entre dans le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/scripts »
make[1]: rien à faire pour « all ».
make[1] : on quitte le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/scripts »
Making all in src
make[1] : on entre dans le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/src »
Making all in libs
make[2] : on entre dans le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/src/libs »
Making all in libclust
make[3] : on entre dans le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/src/libs/libclust »
/bin/bash ../../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I../../../include -g -O2 -fPIC -DPIC -MT div.lo -MD -MP -MF .deps/div.Tpo -c -o div.lo div.c
libtool: compile: gcc -DHAVE_CONFIG_H -I. -I../../../include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I../../../include -g -O2 -fPIC -DPIC -MT div.lo -MD -MP -MF .deps/div.Tpo -c div.c -fPIC -DPIC -o .libs/div.o
libtool: compile: gcc -DHAVE_CONFIG_H -I. -I../../../include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I../../../include -g -O2 -fPIC -DPIC -MT div.lo -MD -MP -MF .deps/div.Tpo -c div.c -o div.o >/dev/null 2>&1
mv -f .deps/div.Tpo .deps/div.Plo
/bin/bash ../../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I../../../include -g -O2 -fPIC -DPIC -MT kdtree.lo -MD -MP -MF .deps/kdtree.Tpo -c -o kdtree.lo kdtree.c
libtool: compile: gcc -DHAVE_CONFIG_H -I. -I../../../include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I../../../include -g -O2 -fPIC -DPIC -MT kdtree.lo -MD -MP -MF .deps/kdtree.Tpo -c kdtree.c -fPIC -DPIC -o .libs/kdtree.o
libtool: compile: gcc -DHAVE_CONFIG_H -I. -I../../../include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I../../../include -g -O2 -fPIC -DPIC -MT kdtree.lo -MD -MP -MF .deps/kdtree.Tpo -c kdtree.c -o kdtree.o >/dev/null 2>&1
mv -f .deps/kdtree.Tpo .deps/kdtree.Plo
/bin/bash ../../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I../../../include -g -O2 -fPIC -DPIC -MT kmeans.lo -MD -MP -MF .deps/kmeans.Tpo -c -o kmeans.lo kmeans.c
libtool: compile: gcc -DHAVE_CONFIG_H -I. -I../../../include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I../../../include -g -O2 -fPIC -DPIC -MT kmeans.lo -MD -MP -MF .deps/kmeans.Tpo -c kmeans.c -fPIC -DPIC -o .libs/kmeans.o
libtool: compile: gcc -DHAVE_CONFIG_H -I. -I../../../include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I../../../include -g -O2 -fPIC -DPIC -MT kmeans.lo -MD -MP -MF .deps/kmeans.Tpo -c kmeans.c -o kmeans.o >/dev/null 2>&1
mv -f .deps/kmeans.Tpo .deps/kmeans.Plo
/bin/bash ../../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I../../../include -g -O2 -fPIC -DPIC -MT metric.lo -MD -MP -MF .deps/metric.Tpo -c -o metric.lo metric.c
libtool: compile: gcc -DHAVE_CONFIG_H -I. -I../../../include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I../../../include -g -O2 -fPIC -DPIC -MT metric.lo -MD -MP -MF .deps/metric.Tpo -c metric.c -fPIC -DPIC -o .libs/metric.o
libtool: compile: gcc -DHAVE_CONFIG_H -I. -I../../../include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/include -I../../../include -g -O2 -fPIC -DPIC -MT metric.lo -MD -MP -MF .deps/metric.Tpo -c metric.c -o metric.o >/dev/null 2>&1
mv -f .deps/metric.Tpo .deps/metric.Plo
/bin/bash ../../../libtool --tag=CC --mode=link gcc -I../../../include -g -O2 -fPIC -DPIC -L/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/src/libsphinxad -L/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/src/libsphinxbase -L/home/thierry/pocketsphinx/sphinxtrain-5prealpha/../sphinxbase-5prealpha/src/libsphinxbase/.libs -o libclust.la div.lo kdtree.lo kmeans.lo metric.lo -lm -lsphinxbase
../../../libtool: eval: line 7977: unexpected EOF while looking for matching `''
../../../libtool: eval: line 7978: syntax error: unexpected end of file
Makefile:357: recipe for target 'libclust.la' failed
make[3]: [libclust.la] Error 2
make[3] : on quitte le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/src/libs/libclust »
Makefile:361: recipe for target 'all-recursive' failed
make[2]: [all-recursive] Error 1
make[2] : on quitte le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/src/libs »
Makefile:361: recipe for target 'all-recursive' failed
make[1]: [all-recursive] Error 1
make[1] : on quitte le répertoire « /home/thierry/pocketsphinx/sphinxtrain-5prealpha/src »
Makefile:457: recipe for target 'all-recursive' failed
make: [all-recursive] Error 1

==========================================

it's seems a libtool problem perhaps same as in this topic :
https://bugs.launchpad.net/ubuntu/+source/libtool/+bug/1002565

PLease help me in this situation, i am completely lost  !!!

**Comment by nshmyrev** [comment]
I told you already, checkout sphinxtrain/sphinxbase/pocketsphinx from github.
