### ISSUE TITLE
error when executing the autogen in ubuntu 

### ISSUE THREAD

**Issue by LakshithaSLT** [cmusphinx/sphinxtrain#44]
```
./configure: line 14407: syntax error near unexpected token `use_lapack=true'
./configure: line 14407: `use_lapack=true'
```

I have tried to figure out the issue by spending many times but without any success.

**Comment by sdulyq** [comment]
yes I meet the same problem, do you solve it?

**Comment by sdulyq** [comment]
I have  solved it！ Just delete the two lines in configure.ac
```
 use_lapack=true
use_internal_lapack=false
```

**Comment by dhdaines** [comment]
Yuck! Autotools is bad.  We use CMake now, so you shouldn't have this problem anymore.
