### ISSUE TITLE
bw.exe breaks on windows

### ISSUE THREAD

**Issue by camhart** [cmusphinx/sphinxtrain#5]
I'm on windows trying to adapt the generic data modules.  I've cloned the repository and built the project using visual studio.  I use bw.exe with the following command and part of the way through execution I get a popup error message that says "bw.exe has stopped working \n A problem caused the program to stop working correctly.  Windows will close the program and notify you if a solution is available".

What's the deal?  I am on 64 bit version of windows.  Does that not work with this?

**Comment by nshmyrev** [comment]
What is the command you run exactly?

**Comment by camhart** [comment]
bw.exe -hmmdir en-us/en-us -moddeffn en-us\en-us\mdef -varnorm no -ts2cbfn
.cont. -feat 1s_c_d_dd -svspec 0-12/13-25/26-38 -cmn current -cmninit
40,3,-1 -agc none -dictfn uppercaseDictionary.txt -ctlfn output.listoffiles
-lsnfn output.transcription -accumdir .

**Comment by nshmyrev** [comment]
`-ts2cbfn` must be `.ptm.`, not `.cont.` I'll probably this crash later.

**Comment by nshmyrev** [comment]
Crash fixed in trunk.
