### ISSUE TITLE
sphinxtrain fails to make on raspberry pi 2

### ISSUE THREAD

**Issue by professorDODO** [cmusphinx/sphinxtrain#7]
log:
```shell```
~/sphinxtrain $ make
Making all in etc
make[1]: Entering directory '/home/pi/sphinxtrain/etc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/sphinxtrain/etc'
Making all in include
make[1]: Entering directory '/home/pi/sphinxtrain/include'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/sphinxtrain/include'
Making all in python
make[1]: Entering directory '/home/pi/sphinxtrain/python'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/sphinxtrain/python'
Making all in scripts
make[1]: Entering directory '/home/pi/sphinxtrain/scripts'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/sphinxtrain/scripts'
Making all in src
make[1]: Entering directory '/home/pi/sphinxtrain/src'
Making all in libs
make[2]: Entering directory '/home/pi/sphinxtrain/src/libs'
Making all in libclust
make[3]: Entering directory '/home/pi/sphinxtrain/src/libs/libclust'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/pi/sphinxtrain/src/libs/libclust'
Making all in libcommon
make[3]: Entering directory '/home/pi/sphinxtrain/src/libs/libcommon'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/pi/sphinxtrain/src/libs/libcommon'
Making all in libio
make[3]: Entering directory '/home/pi/sphinxtrain/src/libs/libio'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/pi/sphinxtrain/src/libs/libio'
Making all in libmllr
make[3]: Entering directory '/home/pi/sphinxtrain/src/libs/libmllr'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/pi/sphinxtrain/src/libs/libmllr'
Making all in libmodinv
make[3]: Entering directory '/home/pi/sphinxtrain/src/libs/libmodinv'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/pi/sphinxtrain/src/libs/libmodinv'
make[3]: Entering directory '/home/pi/sphinxtrain/src/libs'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/pi/sphinxtrain/src/libs'
make[2]: Leaving directory '/home/pi/sphinxtrain/src/libs'
Making all in programs
make[2]: Entering directory '/home/pi/sphinxtrain/src/programs'
Making all in agg_seg
make[3]: Entering directory '/home/pi/sphinxtrain/src/programs/agg_seg'
/bin/bash ../../../libtool --tag=CC   --mode=link gcc -I../../../include -g -O2  -L/home/pi/sphinxtrain/../sphinxbase-0.8/src/libsphinxad 		  -L/home/pi/sphinxtrain/../sphinxbase-0.8/src/libsphinxbase 		  -L/home/pi/sphinxtrain/../sphinxbase-0.8/src/libsphinxbase/.libs -o agg_seg agg_all_seg.o agg_phn_seg.o agg_st_seg.o cnt_phn_seg.o cnt_st_seg.o main.o mk_seg.o parse_cmd_ln.o ../../../src/libs/libio/libio.la ../../../src/libs/libmodinv/libmodinv.la ../../../src/libs/libcommon/libcommon.la ../../../src/libs/libclust/libclust.la ../../../src/libs/libmllr/libmllr.la -lm  -lsphinxbase
libtool: link: gcc -I../../../include -g -O2 -o .libs/agg_seg agg_all_seg.o agg_phn_seg.o agg_st_seg.o cnt_phn_seg.o cnt_st_seg.o main.o mk_seg.o parse_cmd_ln.o  -L/home/pi/sphinxtrain/../sphinxbase-0.8/src/libsphinxbase/.libs -L/home/pi/sphinxtrain/../sphinxbase-0.8/src/libsphinxad -L/home/pi/sphinxtrain/../sphinxbase-0.8/src/libsphinxbase ../../../src/libs/libio/.libs/libio.a ../../../src/libs/libmodinv/.libs/libmodinv.a ../../../src/libs/libcommon/.libs/libcommon.a ../../../src/libs/libclust/.libs/libclust.a ../../../src/libs/libmllr/.libs/libmllr.a -lasound -lpthread -lm /home/pi/sphinxtrain/../sphinxbase-0.8/src/libsphinxbase/.libs/libsphinxbase.so
../../../src/libs/libio/.libs/libio.a(s3map_io.o): In function `s3map_write':
/home/pi/sphinxtrain/src/libs/libio/s3map_io.c:152: undefined reference to `bio_fwrite_1d'
collect2: ld returned 1 exit status
Makefile:336: recipe for target 'agg_seg' failed
make[3]: *** [agg_seg] Error 1
make[3]: Leaving directory '/home/pi/sphinxtrain/src/programs/agg_seg'
Makefile:321: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/pi/sphinxtrain/src/programs'
Makefile:287: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/sphinxtrain/src'
Makefile:379: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by nshmyrev** [comment]
What sphinxtrain and what sphinxbase version do you have

**Comment by professorDODO** [comment]
sphinxbase-0.8 and sphinxtrain was git cloned just minutes ago, don't know the version.

**Comment by nshmyrev** [comment]
You need sphinxbase from git

**Comment by professorDODO** [comment]
Thanks, that worked
