### ISSUE TITLE
cannot find the corresponding hmm during "sphinxtrain run"

### ISSUE THREAD

**Issue by liangnet** [cmusphinx/sphinxtrain#9]
I got an error that
MODULE: DECODE Decoding using models previously trained
        Decoding 3 segments starting at 0 (part 1 of 1) 
        0% ERROR: FATAL: "batch.c", line 822: PocketSphinx decoder init failed

ERROR: This step had 1 ERROR messages and 0 WARNING messages.  Please check the log file for details.
ERROR: Failed to start pocketsphinx_batch
        Aligning results to find error rate
Can't open ./test_train_sphinx/result/去你媽的擔擔麵-1-1.match
word_align.pl failed with error code 65280 at /usr/local/lib/sphinxtrain/scripts/decode/slave.pl line 173.

So, I checked th the log in logdir/decode/去你媽的擔擔麵.log
I saw the line 

-hmm ./test_train_sphinx/model_parameters/去你媽的擔擔麵.cd_cont_200

The substring _200 is generated by 

\# Models to use.
$DEC_CFG_MODEL_NAME = "$CFG_EXPTNAME.cd_${CFG_DIRLABEL}_${CFG_N_TIED_STATES}";

in sphinxt_train.cfg

IS IT A BUG???????

**Comment by liangnet** [comment]
Another Issue.
I tried to remove the _${CFG_N_TIED_STATES} and other error is output!
This error is from cd_ at the same line in sphinx_train.cfg
I want to train a simple wakeup command so that I only record three utterances.
After typing "sphinxtrain run" and pressing the enter key, immediately, I see the training mode was change to ci instead of cd, but latter step seems to be not change the hmm model type.

**Comment by nshmyrev** [comment]
You do not have enough data for training as recommended by acoustic model training tutorial. You can download [TCHS dataset](http://www.openslr.org/18/) for training instead.
